name: notebook
description: An example on how to use the auto_stories package.
publish_to: none
version: 0.0.0+0

environment: { sdk: ^3.7.0, flutter: ">=3.29.0" }

dependencies:
  auto_stories: { path: ../ }
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
