name: auto_stories
description: Auto generate data and widget stories preview once file changed.
repository: https://github.com/aprosail/auto-stories
version: 0.0.2
environment: { sdk: "^3.7.0", flutter: ">=3.29.0" }

dependencies:
  analyzer: ^7.3.0
  flutter: { sdk: flutter }
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test: { sdk: flutter }
  test: ^1.25.15
