name: auto_stories
description: Auto generate widget preview to improve development experience.
version: 0.0.1
environment: {sdk: ^3.7.0, flutter: ">=3.29.0"}
repository: https://github.com/aprosail/auto-stories

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}

flutter:
  uses-material-design: false
