/// Annotations that tell `package:auto_stories` how to generate code.
library;

/// A type for all annotations here, like a generics.
mixin AutoStoriesAnnotation {
  /// Library identifier of current file,
  /// where all annotations in `package:auto_stories` are defined.
  static const library = 'package:auto_stories/gen/annotations.dart';

  /// Static name of this [AutoStoriesAnnotation] mixin.
  static const mixinName = 'AutoStoriesAnnotation';
}

/// Annotate that current range is auto generated by `package:auto_stories`.
/// Such code will be auto-generated once file saved,
/// and it's strongly not recommended to modify it manually.
const generated = Generated();

/// Static name of the [generated] instance.
const generatedInstanceName = 'generated';

/// An annotation that tells the following contents are auto generated,
/// especially inside the source code.
final class Generated with AutoStoriesAnnotation {
  /// It's strongly recommended to use the shortcut instance [generated]
  /// rather than call this constructor, which contains no parameters.
  const Generated();

  /// Static name of the [Generated] class.
  static const className = 'Generated';
}
