name: publish-pub

on:
  push: { tags: ["v[0-9]+.[0-9]+.[0-9]+*"] }

jobs:
  publish:
    runs-on: ubuntu-latest
    env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
    permissions: { id-token: write, contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with: { channel: stable, version: 3.29.0 }
      - uses: flutter-actions/setup-pubdev-credentials@v1
      - run: dart pub get
      - run: sh review.sh

      - name: publish to pub.dev
        run: dart pub publish --force

      - name: create release
        run: "gh release create ${{ github.ref_name }} \
          --title ${{ github.ref_name }} \
          --notes-file .changelog.md"
