name: review

on:
  pull_request: { branches: [main] }
  push: { branches: [main] }

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with: { channel: stable, version: 3.29.0 }
      - run: dart pub get
      - run: sh review.sh
